name: nova-blueprint

services:
  nova-blueprint:
    image: ${VALIDATOR_IMAGE:-shadeform/nova-blueprint:latest}
    container_name: nova-blueprint
    restart: "no"
    working_dir: /app
    gpus: all
    volumes:
      - ./:/app:rw
      - ${BT_WALLETS_DIR:-$HOME/.bittensor/wallets}:/wallets:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: ["python", "neurons/validator/validator.py", "--logging.debug"]

